# Results

We now do some analysis of the VIX and the return for the market.Here we see little relationship between daily returns and the level of the VIX - although at extremely high levels there may be a small negative relationship.

```{r}
library(tidyverse)
vix = read.csv("https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX_History.csv")
ff = read_csv("ff.csv")

vix$DATE = as.Date(vix$DATE,format='%m/%d/%Y')
#ind$DATE = as.Date(ind$X,format='%Y%m%d')
#recession$DATE = as.Date(recession$date,format='$Y-$d-$m')
ff$DATE = as.Date(as.character(ff$X),format='%Y%m%d')

df <-  merge(vix,ff,by= c("DATE" = "DATE")) #%>% merge(rec_d,by=c("DATE"="DATE"))

ggplot(df,aes(x=CLOSE,y=Mkt.RF)) + geom_point() + geom_smooth()

df1 <- df %>% mutate(bin=cut_width(CLOSE,5))
ggplot(df1,aes(x=CLOSE,y=Mkt.RF)) + geom_point( alpha = 0.2,shape=1,position = "jitter")  +geom_boxplot(aes(group=bin)) + geom_smooth()
```


So we can see a slight correlation - now we look at changes in the VIX vs changes in returns.

```{r}


df1 <- df %>% mutate(dVIX=CLOSE - lag(CLOSE))
ggplot(df1,aes(x=dVIX,y=Mkt.RF)) + geom_point( alpha = 0.2,shape=1,position = "jitter") + geom_smooth()

df2 <- df1 %>% mutate(dVIX_t1=lag(dVIX))
ggplot(df2,aes(x=dVIX_t1,y=Mkt.RF)) + geom_point( alpha = 0.2,shape=1,position = "jitter") + geom_smooth()
```

